<?php

namespace api\models\form;

use api\models\User;
use yii\base\Model;
use yii\web\UnauthorizedHttpException;

class ChangeMailForm extends Model
{
    public $email;
    public function rules()
    {
        return [
            [
                'email','email'
            ],
            [
                'email','required'
            ],
            [
                'email', 'unique',
                'targetClass' => User::className(),
                'targetAttribute' => 'email',
                'filter' => [
                    'status' => User::STATUS_ACTIVE
                ]
            ]
        ];
    }
    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }
    public function generateCodeVerify($userId){
        if(!$this->validate())
            return false;
        if($user = User::findOne($userId)){
            $user->generateCodeChangeMail();
            $user->save();
            $user->sendCodeChangeMail($this->email);
            return true;
        }
        else
        {
            throw new UnauthorizedHttpException(\Yii::t("app","Token is expire"));
        }

    }
}