<?php

namespace api\models\form;

use common\libs\Constants;
use Yii;
use api\models\User;
use yii\base\Model;

class SignupForm extends Model
{
    public $username;
    public $email;
    public $phone;
    public $password;
    public $rePassword;
    public $parentCode;
    public $name;


    public function rules()
    {
        return [
            [
                'username', 'filter', 'filter' => 'trim'
            ],
            [
                ['username','name'], 'required'
            ],
            [
                'username',
                'unique',
                'targetClass' => User::className(),
            ],
            [
                ['username','name'], 'string', 'min' => 6, 'max' => 255
            ],
            [
                'parentCode', 'string'
            ],

            ['email', 'filter', 'filter' => 'trim'],
            [
                'email', 'required'
            ],
            [
                'email', 'email'
            ],
            [
                'email', 'string', 'max' => 255
            ],
            [
                'email',
                'unique',
                'targetClass' => User::className(),
            ],

            [
                ['password','rePassword'], 'required'
            ],
            [
                ['password','rePassword'], 'string', 'min' => 8
            ],
            [
                ['rePassword'], 'compare', 'compareAttribute'=>'password', 'message'=> Yii::t("app","Password don't match")
            ]
        ];
    }

    public function attributeLabels()
    {
        return [
            'username' => Yii::t('app', 'Username'),
            'email' => Yii::t('app', 'Email'),
            'phone' => Yii::t('app', 'Phone'),
            'password' => Yii::t('app', 'Password'),
            'rePassword' => Yii::t('app', 'Re Password'),
            'parentCode' => Yii::t('app', 'Parent Code'),
            'name' => Yii::t('app', 'Name'),
        ];
    }

    public function signup()
    {
        if (!$this->validate()) {
            return null;
        }

        $user = new User();
        $user->loadDefaultValues();
        $user->username = $this->username;
        $user->email = $this->email;
        $user->name = $this->name;
        $user->verify_email = Constants::YesNo_Yes;
        $user->parent_id = User::findByCode($this->parentCode)->id ?? null;
        $user->setPassword($this->password);
        $user->generateAuthKey();
//        $user->generateEmailVerifyToken();
        if($user->validate() && $user->save()){
//            $user->sendMailConfirm();
            return $user;
        }
        return false;
    }

    public function afterValidate()
    {
        $parent = User::findByCode($this->parentCode);
        if(!$parent){
            $this->addError('parentCode', Yii::t('app','Mã giới thiệu không tồn tại'));
        }
        parent::afterValidate(); // TODO: Change the autogenerated stub
    }
}