<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    "Buy product {name} success" => "Mua sản phẩm {name} thành công",
    "Product not found" => "Sản phẩm không tồn tại trên hệ thống",
    "Use ticket success, please wait for the shop owner to approve" => "Sử dụng vé mua hàng thành công, vui lòng đợi chủ shop duyệt",
    "Shop not found" => "Cửa hàng không tồn tại trên hệ thống",
    "Buy product fail" => "Mua sản phẩm không thành công, vui lòng thử lại",
    "Buy ticket success" => "Mua vé vào cửa thành công",
    "Please use ticket to view shop" => "Vui lòng sử vé để xem sản phẩm của cửa hàng",
    "Please wait for the shop owner to approve" => "Vui lòng đợi chủ shop duyệt vé vào của bạn",
    "Login fail" => "Đăng nhập không thành công",
    "Login success" => "Đăng nhập thành công",
    "Sign up success" => "Đăng kí thành công",
    "Sign up fail" => "Đăng kí không thành công, vui lòng thử lại sau",
    "Email has sent success" => "Email xác nhận đã được gửi, vui lòng kiểm tra hộp thư điện tử của bạn, hãy kiểm cả mục junk/spam nhé",
    "Failed to send email" => "Lỗi trong quá trình gửi email, vui lòng thử lại sau",
    "Password don't match" => "Mật khẩu không trùng khớp",
    "Parent Code" => "Mã người giới thiệu",
    "Re Password" => "Mật khẩu nhập lại",
    "Name" => "Tên đầy đủ",
    "Password" => "Mật khẩu",
    "Username" => "Tên đăng nhập",
    "{attribute} is required" => "Vui lòng điền {attribute}.",
    'User not found' => 'Tài khoản không tồn tại',
    "Bank Account Name" => "Tên tài khoản",
    "Email be blank." => "Vui lòng điền email xác minh",
    "Email not valid" => "Email không hợp lệ hoặc không tồn tại, vui lòng kiểm tra lại",
    "Email has been verified." => "Email đã được xác nhận.",
    "Update info success" => "Cập nhật thông tin thành công",
    "Change info failed" => "Đổi thông tin không thành công, vui lòng kiểm tra lại",
    "Change password failed" => "Đổi mật khẩu không thành công, vui lòng kiểm tra lại",
    "Change password success" => "Đổi mật khẩu thành công",
    "Deposit queue success, please transfer to qr code" => "Tạo yêu cầu nạp tiền thành công, hãy chuyển tiền vào thông tin này!",
    "Deposit failed" => "Tạo yêu cầu nạp tiền không thành công. Vui lòng thử lại sau!",
    "Withdraw failed" => "Yêu cầu rút tiền không thành công, Vui lòng liên hệ admin để được hỗ trợ!",
    "Withdraw queue success, please wait for admin to approve" => "Yêu cầu rút tiền thành công, chúng tôi sẽ xử lý trong thời gian sớm nhất!",
    "OTP has send to your new email" => "Mã xác nhận đã được gửi tới email mới của bạn, vui lòng kiểm tra email (Hộp thư đến/Hộp thư rác)!",
    "Token not valid" => "Mã truy cập không hợp lệ",
    "Your deposit request is pending" => "Yêu cầu nạp của bạn đang đợi duyệt! Chúng tôi sẽ duyệt sớm nhất cho bạn!",
    "System has deposited {amount} to your account, Please check your transaction" => "Hệ thống đã nhận được số tiền {amount} của bạn. Hãy kiểm tra lại số dư tài khoản!",
    "Your deposit request is cancelled" => "Yêu cầu của bạn đã từ chối!",
    "Your deposit request is not valid" => "Yêu cầu nạp tiền của bạn hợp lệ!",
    "Code not found" => "Mã không tồn tại",
    'Ticket Commission Month' => 'Hoa hồng vé tháng',
    'NFT Commission Month' => 'Hoa hồng NFT tháng',
    'You have not purchased your ticket to the store or your ticket has not had enough time to purchase' => 'Bạn chưa mua vé vào cửa hàng hoặc vé của bạn chưa đủ thời gian để mua hàng',
    "You don't have enough balance to buy {product_name} product" => 'Bạn không có đủ tiền để mua sản phẩm {product_name}',
    'Receive Expiration' => 'Hết hạn nhận hàng',
    'Order {order_code} is impossible to take' => 'Đơn hàng {order_code} là không thể lấy',
    'Order {order_code} is not exists' => 'Đơn hàng {order_code} không tồn tại',
    'Error resell order {order_code}' => 'Lỗi bán lại đơn hàng {order_code}',
    'Order {order_code} is not resold' => 'Đơn hàng {order_code} không được bán lại',
    'Error create order' => 'Lỗi tạo đơn hàng',
    'Error receiving order' => 'Lỗi nhận đơn hàng',
    'You have not received this product' => 'Bạn chưa thể nhận đơn hàng này',
    'The balance in your withdrawal wallet is not enough' => 'Số dư trong ví rút của bạn không đủ',
];
