<?php

namespace common\models;

use common\libs\Constants;
use Yii;
use yii\helpers\VarDumper;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "user".
 *
 * @property int $id user id(auto increment)
 * @property string $username username
 * @property string $auth_key auth key for generate logged in cookie
 * @property string $password_hash crypt password
 * @property string $password_reset_token reset password temp token
 * @property string $email user email
 * @property string $avatar avatar url
 * @property string $access_token token
 * @property int $status user status, (normal:10)
 * @property int $branch_id Branch
 * @property int $created_at created at
 * @property int $updated_at updated at
 */
class User extends BaseModel implements \yii\web\IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;
    public $password;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['username',  'email', 'created_at', 'updated_at'], 'required'],
            [['status', 'created_at', 'updated_at'], 'integer'],
            [['username', 'password_hash','password', 'password_reset_token', 'email', 'avatar'], 'string', 'max' => 255],
            [['auth_key'], 'string', 'max' => 32],
            [['access_token'], 'string', 'max' => 42],
            [['username'], 'unique'],
            [['email'], 'unique'],
            ['password', 'string', 'min' => 6, 'skipOnEmpty' => true],
            [['password_reset_token'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'user id(auto increment)'),
            'username' => Yii::t('app', 'username'),
            'auth_key' => Yii::t('app', 'auth key for generate logged in cookie'),
            'password_hash' => Yii::t('app', 'crypt password'),
            'password_reset_token' => Yii::t('app', 'reset password temp token'),
            'email' => Yii::t('app', 'user email'),
            'avatar' => Yii::t('app', 'avatar url'),
            'access_token' => Yii::t('app', 'token'),
            'status' => Yii::t('app', 'user status, (normal:10)'),
            'created_at' => Yii::t('app', 'created at'),
            'updated_at' => Yii::t('app', 'updated at'),
//            'branch_id' => Yii::t('app', 'Branch'),
        ];
    }

    public static function findIdentity($id)
    {
        return User::findOne(['id' => $id, 'status' => User::STATUS_ACTIVE]);
    }
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return User::findOne(['auth_key' => $token, 'status' => User::STATUS_ACTIVE]);
    }

    public function getId()
    {
        return $this->id;
    }

    public function getAuthKey()
    {
        return $this->auth_key;
    }

    public function validateAuthKey($authKey)
    {
        if ($this->auth_key == $authKey) {
            return true;
        }
        return false;
    }
    public  function getThongTinHocSinh()
    {
        return $this->hasOne(ThongTinHocSinh::className(), ['id' => 'user_id']);
    }
    public function validate($attributeNames = null, $clearErrors = true)
    {
        if($this->id == null || $this->id == 0){
            if($this->password!= ""){
                $this->addError("password", Yii::t('app','password not set'));
            }
        }
        return parent::validate($attributeNames, $clearErrors); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {

        if($this->password != ""){
            $this->password_hash = Yii::$app->security->generatePasswordHash($this->password);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public static function findByUsername($username)
    {
        return User::findOne(['username' => $username, 'status' => User::STATUS_ACTIVE]);
    }
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }
    public function login()
    {
        $this->auth_key = Yii::$app->getSecurity()->generateRandomString();
        $this->save();
        return Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600 * 24 * 30 : 0);
    }

}
