<?php

namespace backend\widgets;

use kartik\number\NumberControl as NumberControllerBase;

class MoneyControl extends NumberControllerBase{
    public function init()
    {
        $this->maskedInputOptions = [
            'prefix' => \Yii::$app->formatter->currencyCode,
            'suffix' => '',
            'allowMinus' => true,
            'groupSeparator' => ',',
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}