<?php

namespace backend\widgets;

use kartik\number\NumberControl as NumberControllerBase;

class NumberControl extends NumberControllerBase{
    public function init()
    {
        $this->maskedInputOptions = [
            'prefix' => '',
            'suffix' => ' ',
            'allowMinus' => true,
            'groupSeparator' => ',',
            'digits' => 3,
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}